config/routes.rb
Rails.application.routes.draw do

  resources :circles
  root 'static_pages#index'

  get 'signup', to: 'users#new'
  get 'account', to: 'users#show'
  get 'account/setting', to: 'users#edit'
  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def circle_suggest
    code = ""
    current_user.tags.each do |tag|
      code += "<div class='row'><div class='col-12'><div style='background:#1f1f1f;color:#ffffff;padding:5px 15px;'>#{tag.name}</div></div></div>";
      code += "<div class='row'>"
      tag.circles.each do |circle|
        code += circle_view(circle)
      end
      code += "</div>"
    end
    code
  end
  private
  def circle_view(circle)
    code = "<div class='col-6'>"
    code += "<div style='position:relative;width:100%;height:100%'>"
    code += "<a href='/circles/#{circle.id}'>"
    code += "<img src='https://mb.api.cloud.nifty.com/2013-09-01/applications/6aJWFXEYlhr6utde/publicFiles/#{circle.id}.jpg' style='width:100%;height:auto;'>"
    code += "</a>"
    code += "<div style='position:absolute;left:10px;bottom:10px;color:#ffffff;font-size:2em;text-shadow: 0 0 3px black;'>#{circle.name}</div></a>"
    code += "</div>"
    code += "</div>"
    code
  end
end

app/views/static_pages/index.html.erb
<div class="container">
  <div class="row">
      <% if logged_in? %>
        <div class="col-12">
        <%= link_to '新しくサークルを登録する', new_circle_path, class: "btn btn-info", style: "color:#ffffff;width:100%;" %>
        </div>
      <% else %>
        <div class="col-6">
          <%= link_to 'ログインする', login_path, class: "btn btn-info", style: "color:#ffffff;width:100%;" %>
        </div>
        <div class="col-6">
          <%= link_to '新規登録する', signup_path, class: "btn btn-primary", style: "color:#ffffff;width:100%;" %>
        </div>
      <% end %>
    </div>
  <% if logged_in? %>
    <%= raw(circle_suggest) %>
  <% else %>
    <%= raw(circle_list) %>
  <% end %>
</div>