config/routes.rb
Rails.application.routes.draw do

  resources :circles
  root 'static_pages#index'

  get 'signup', to: 'users#new'
  get 'account', to: 'users#show'
  get 'account/setting', to: 'users#edit'
  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email.downcase!}
  validates :display_name,
            presence: true,
            length: {maximum: 25}
  validates :family_name,
            presence: true,
            length: {maximum: 25}
  validates :first_name,
            presence: true,
            length: {maximum: 25}
  validates :email,
            presence: true,
            length: {maximum: 255},
            format: {with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i},
            uniqueness: {case_sensitive: false}
  validates :password,
            presence: true,
            length: {minimum: 6},
            allow_nil: true
  validates :student_number,
            presence: true,
            format: {with: /\A(0[0-9]|10)1[0-8][0-9]{5}\z/i}
  validates :phone,
            format: {with: /\A(080|090)[0-9]{8}\z/i},
            allow_nil: true
  has_secure_password
  has_many :users_circles, dependent: :destroy
  has_many :circles, through: :users_circles
  has_many :users_tags, dependent: :destroy
  has_many :tags, through: :users_tags
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :unless_login, only: [:new, :create]
  before_action :require_login, only: [:show, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    redirect_to account_path
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    set_available_tags_to_gon
  end

  # GET /users/1/edit
  def edit
    gon.tag_list = current_user.tags
    set_available_tags_to_gon
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      set_tags @user
      login @user
      redirect_to account_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if current_user.update(user_params)
      set_tags current_user
      redirect_to current_user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    def set_tags(user)
      user.users_tags.destroy_all
      params[:user][:tag_list].split(",").each do |name|
        tag = Tag.find_by(name: name)
        tag = Tag.create(name: name) unless tag
        UsersTag.create(user_id: user.id, tag_id: tag.id)
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:display_name, :family_name, :first_name, :email, :student_number, :phone, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <table class="table tables-bordered table-striped">
      <tr>
        <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
          表示名
        </th>
        <td align="left" valign="middle" colspan="2">
          <%= form.text_field :display_name, id: :user_display_name, class: "form-control" %>
        </td>
        <td align="left" valign="middle">
          【例】Taro
        </td>
      </tr>
      <tr>
        <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
          名前
        </th>
        <td align="left" valign="middle">
          <%= form.text_field :family_name, id: :user_family_name, class: "form-control", placeholder:"姓" %>
        </td>
        <td align="left" valign="middle">
          <%= form.text_field :first_name, id: :user_first_name, class: "form-control", placeholder:"名" %>
        </td>
        <td align="left" valign="middle">
          【例】山田　大郎
        </td>
      </tr>
      <tr>
        <th align="right" valign="middle" style="width:12.5%;background:#74DF00;color: #ffffff;">
          Eメール
        </th>
        <td align="left" valign="middle" colspan="2">
          <%= form.text_field :email, id: :user_email, class: "form-control" %>
        </td>
        <td align="left" valign="middle">
          【例】yamada_taro@example.com
        </td>
      </tr>
      <tr>
        <th align="right" valign="middle" style="width:12.5%;background:#74DF00;color: #ffffff;">
          学籍番号
        </th>
        <td align="left" valign=",odd;e" colspan="2">
          <%= form.text_field :student_number, id: :user_student_number, class: "form-control" %>
        </td>
        <td align="left" valign="middle">
          【例】123456789
        </td>
      </tr>
      <tr>
        <th align="right" valign="middle" style="width:12.5%;background:#74DF00;color: #ffffff;">
          電話番号（任意）
        </th>
        <td align="left" valign=",odd;e" colspan="2">
          <%= form.text_field :phone, id: :user_phone, class: "form-control" %>
        </td>
        <td align="left" valign="middle">
          【例】08012345678
        </td>
      </tr>
      <tr>
        <th align="right" valign="middle" style="width:12.5%;background:#74DF00;color: #ffffff;">
          興味があること
        </th>
        <td align="left" valign=",odd;e" colspan="2">
          <ul id="favo-tags" class="form-control"></ul>
        </td>
        <td align="left" valign="middle">
          単語で1つ以上
        </td>
      </tr>
      <tr>
        <th align="right" valign="middle" style="width:12.5%;background:#74DF00;color: #ffffff;">
          パスワード
        </th>
        <td align="left" valign=",odd;e" colspan="2">
          <%= form.password_field :password, id: :user_password, class: "form-control" %>
        </td>
        <td align="left" valign="middle">
          半角数字6文字以上
        </td>
      </tr>
      <tr>
        <th align="right" valign="middle" style="width:12.5%;background:#74DF00;color: #ffffff;">
          パスワード確認
        </th>
        <td align="left" valign=",odd;e" colspan="2">
          <%= form.password_field :password_confirmation, id: :user_password_confirmation, class: "form-control" %>
        </td>
        <td align="left" valign="middle">
          上に同じ
        </td>
      </tr>
    </table>

    <br></br>
    <div style="text-align:center;">
      <%= form.submit "OK",class:"btn btn-primary" %>
    </div>

<% end %>

<script type="text/javascript">
    $(document).on('turbolinks:load', function(){
        all_available_tags = [];
        if(gon.available_tags) all_available_tags = gon.available_tags;
        $('#favo-tags').tagit(
            {
                singleField: true,
                fieldName: 'user[tag_list]',
                availableTags: all_available_tags
            }
        );
        if(gon.tag_list){
            for(var i=0;i<gon.tag_list.length;i++){
                $('#favo-tags').tagit('createTag', gon.tag_list[i]["name"]);
            }
        }
    });
</script>

app/views/users/edit.html.erb
<div class="container" style="padding: 80px 0;">
  <h1>プロフィール編集</h1>
  <hr color="49b77c">
  <%= render 'form', user: current_user %>

  <p>
    <%= link_to 'ログアウト', logout_path, method: :delete, class:"btn btn-danger", style:"color:#ffffff" %>
  </p>

</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Display name</th>
      <th>Name</th>
      <th>Email</th>
      <th>Student number</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.display_name %></td>
        <td><%= user.family_name %> <%= user.first_name %></td>
        <td><%= user.email %></td>
        <td><%= user.student_number %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', signup_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<div class="container" style="padding: 80px 0;">
  <h1>アカウント</h1>
  <hr color="49b77c">
  <table class="table tables-bordered table-striped">
    <tr>
      <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
        表示名
      </th>
      <td align="left" valign="middle">
        <%= current_user.display_name %>
      </td>
    </tr>
    <tr>
      <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
        名前
      </th>
      <td align="left" valign="middle">
        <%= current_user.family_name %> <%= current_user.first_name %>
      </td>
    </tr>
    <tr>
      <th align="right" valign="middle" style="width:12.5%;background:#74DF00;color: #ffffff;">
        Eメール
      </th>
      <td align="left" valign="middle">
        <%= current_user.email %>
      </td>
    </tr>
    <tr>
      <th align="right" valign="middle" style="width:12.5%;background:#74DF00;color: #ffffff;">
        学籍番号
      </th>
      <td align="left" valign="middle">
        <%= current_user.student_number %>
      </td>
    </tr>
    <tr>
      <th align="right" valign="middle" style="width:12.5%;background:#74DF00;color: #ffffff;">
        電話番号（任意）
      </th>
      <td align="left" valign="middle">
        <%= current_user.phone %>
      </td>
    </tr>
    <tr>
      <th align="right" valign="middle" style="width:12.5%;background:#74DF00;color: #ffffff;">
        所属サークル
      </th>
      <td align="left" valign="middle">
        <% current_user.circles.each do |circle| %>
            <p><%= link_to circle.name, circle %></p>
        <% end %>
      </td>
    </tr>
    <tr>
      <th align="right" valign="middle" style="width:12.5%;background:#74DF00;color: #ffffff;">
        興味があること
      </th>
      <td align="left" valign="middle">
        <% current_user.tags.each do |tag| %>
            <%= tag.name %>
        <% end %>
      </td>
    </tr>
  </table>
  <p>
    <%= link_to '編集', account_setting_path, class:"btn btn-primary", style:"color:#ffffff;width:100%;" %>
  </p>
  <p>
    <%= link_to 'ログアウト', logout_path, method: :delete, class:"btn btn-danger", style:"color:#ffffff" %>
  </p>
  <p>
    <%= link_to 'トップにもどる', root_path, class:"btn btn-primary", style:"color:#ffffff" %>
  </p>
</div>