config/routes.rb
Rails.application.routes.draw do

  resources :circles
  root 'static_pages#index'

  get 'signup', to: 'users#new'
  get 'account', to: 'users#show'
  get 'account/setting', to: 'users#edit'
  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/circle.rb
class Circle < ApplicationRecord
  validates :name,
            presence: true,
            length: {minimum: 2}
  validates :profile,
            presence: true
  validates :cost,
            presence: true
  has_many :users_circles, dependent: :destroy
  has_many :users, through: :users_circles
  has_many :circles_tags,dependent: :destroy
  has_many :tags, through: :circles_tags
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  before_action :set_circle, only: [:show, :edit, :update, :destroy, :new_member, :create_member]
  before_action :require_login

  # GET /circles
  # GET /circles.json
  def index
    @circles = Circle.all
  end

  # GET /circles/1
  # GET /circles/1.json
  def show
    gon.image_path = @circle.id
  end

  # GET /circles/new
  def new
    @circle = Circle.new
    set_available_tags_to_gon
  end

  # GET /circles/1/edit
  def edit
    gon.tag_list = @circle.tags
    set_available_tags_to_gon
  end

  # POST /circles
  # POST /circles.json
  def create
    @circle = Circle.new(circle_params)
    if @circle.save
      @user_circle = UsersCircle.new(user_id: current_user.id, circle_id: @circle.id)
      set_tags @circle
      if @user_circle.save
        redirect_to @circle, notice: 'Circle was successfully created.'
      else
        render :new
      end
    else
      render :new
    end
  end

  # PATCH/PUT /circles/1
  # PATCH/PUT /circles/1.json
  def update
    if @circle.update(circle_params)
      set_tags @circle
      redirect_to @circle, notice: 'Circle was successfully updated.'
    else
      render :edit
    end
  end

  def new_member
  end

  def create_member
    @user_circle = UsersCircle.new(user_id: User.find_by(email: params[:new_member][:email]).id, circle_id: @circle.id)
    if @user_circle.save
      redirect_to @circle, notice: 'Circle was successfully created.'
    else
      flash.now[:danger] = "そのメールアドレスは間違っています"
      render :new_member
    end
  end

  # DELETE /circles/1
  # DELETE /circles/1.json
  def destroy
    @circle.destroy
    redirect_to circles_url, notice: 'Circle was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_circle
      @circle = Circle.find(params[:id])
    end
    def set_tags(circle)
      circle.circles_tags.destroy_all
      params[:circle][:tag_list].split(",").each do |name|
        tag = Tag.find_by(name: name)
        tag = Tag.create(name: name) unless tag
        CirclesTag.create(circle_id: circle.id, tag_id: tag.id)
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def circle_params
      params.require(:circle).permit(:name, :profile, :intercollege, :cost)
    end
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/views/circles/_form.html.erb
<%= form_with(model: circle, local: true) do |form| %>
  <% if circle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(circle.errors.count, "error") %> prohibited this circle from being saved:</h2>

      <ul>
      <% circle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <table class="table tables-bordered table-striped">
      <tr>
        <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
          サークル名
        </th>
        <td align="left" valign="middle" colspan="2">
          <%= form.text_field :name, id: :circle_name, class: "form-control" %>
        </td>
        <td align="left" valign="middle">
          25文字以下で指定
        </td>
      </tr>
      <tr>
        <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
          インカレサークル
        </th>
        <td align="left" valign="middle" colspan="2">
          <label><%= form.check_box :intercollege, id: :circle_intercollege %>このサークルはインカレです。</label>
        </td>
        <td align="left" valign="middle">
          他大学生アカウントからの連絡を許可します
        </td>
      </tr>
      <tr>
        <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
          年会費
        </th>
        <td align="left" valign="middle" colspan="2">
          <%= form.number_field :cost, id: :circle_cost, class: "form-control", style: "display:inline;width:80%" %>円
        </td>
        <td align="left" valign="middle">

        </td>
      </tr>
      <tr>
        <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
          タグ付け
        </th>
        <td align="left" valign="middle" colspan="2">
          <ul id="feat-tags" class="form-control"></ul>
        </td>
        <td align="left" valign="middle">
          最大20コまで
        </td>
      </tr>
      <tr>
        <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
          PR
        </th>
        <td align="left" valign="middle" colspan="3">
          <%= form.text_area :profile, id: :circle_profile, class: "form-control", rows: 20 %><br>
          このPRも検索内容に使用されます。できるだけ詳細に記入ください。<br>
          ※他者の誹謗中傷や個人情報の開示など法に抵触する文章の記入はおやめください。
        </td>
      </tr>
    </table>
    <br></br>
    <div style="text-align:center;">
      <%= form.submit "OK", class:"btn btn-primary" %>
    </div>
<% end %>

<script type="text/javascript">
    $(document).on('turbolinks:load', function(){
        all_available_tags = [];
        if(gon.available_tags) all_available_tags = gon.available_tags;
        $('#feat-tags').tagit(
            {
                singleField: true,
                fieldName: 'circle[tag_list]',
                availableTags: all_available_tags
            }
        );
        if(gon.tag_list){
            for(var i=0;i<gon.tag_list.length;i++){
                $('#feat-tags').tagit('createTag', gon.tag_list[i]["name"]);
            }
        }
    });
</script>

app/views/circles/edit.html.erb
<div class="container" style="padding: 80px 0;">
  <h1>サークル編集</h1>
  <hr color="49b77c">
  <%= render 'form', circle: @circle %>
  <%= link_to 'Destroy', @circle, method: :delete, data: { confirm: '削除してもよろしいですか？' } %>
  <%= link_to 'Show', @circle %> |
  <%= link_to 'Back', circles_path %>
</div>

app/views/circles/index.html.erb
<%= raw(circle_list) %>

app/views/circles/new.html.erb
<div class="container" style="padding: 80px 0;">
  <h1>サークル作成</h1>
  <hr color="49b77c">

  <%= render 'form', circle: @circle %>

<%= link_to 'Back', circles_path %>
</div>

app/views/circles/new_member.html.erb
<div class="container" style="padding: 80px 0;">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= form_for(:new_member, url:create_member_path) do |f| %>
    <div style="padding: 50px; margin-bottom: 40px; border: 1px solid #333333; box-shadow: 4px 4px 8px #dddddd;">
      <h1><%= @circle.name %>へ追加</h1>
      <div class="form-group">
        <%= f.label "Eメールアドレス" %>
        <%= f.email_field :email, class:"form-control", placeholder:"Eメールアドレス" %>
      </div>
      <%= f.submit "招待する" %>
    </div>
  <% end %>
</div>

app/views/circles/show.html.erb
<script type="text/javascript">
  <!--
  var ncmb = new NCMB("40eba54f0b6c3280251ab4d2ce4d888bf0c94ea220670ed380deaa4cd3084951", "601aeb8e880348637550fc71c25ca602a7acd430e8bc7192fdfe1361df591ccd");

  var onFormSend = function(){
      var fileName = gon.image_path+".jpg";
      var fileData = document.getElementById("file-data").files[0];

      ncmb.File.upload(fileName, fileData)
          .then(function(res){
              alert("アップロード完了！");
              document.getElementById("circle-image").innerHTML = "<img src='https://mb.api.cloud.nifty.com/2013-09-01/applications/6aJWFXEYlhr6utde/publicFiles/"+gon.image_path+".jpg' style='width:100%'>";
          })
          .catch(function(err){
              alert("アップロードに失敗しました");
          });
  }
  //-->
</script>

<div class="container-fluid">
  <div class="row">
    <div class="col-6">
      <p id="notice"><%= notice %></p>
      <div style="font-size:3em"><%= @circle.name %></div>
      <table class="table tables-bordered table-striped">
        <tr>
          <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
            PR
          </th>
          <td align="left" valign="middle">
            <%= @circle.profile %>
          </td>
        </tr>
        <tr>
          <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
            インカレ
          </th>
          <td align="left" valign="middle">
            <%= @circle.intercollege ? "インカレです": "名大限定です" %>
          </td>
        </tr>
        <tr>
          <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
            年会費用
          </th>
          <td align="left" valign="middle">
            <%= @circle.cost %>円
          </td>
        </tr>
        <tr>
          <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
            人数
          </th>
          <td align="left" valign="middle">
            <%= @circle.users.count %>人
          </td>
        </tr>
        <tr>
          <th align="right" valign="middle" style="width:20%;background:#74DF00;color: #ffffff;">
            メンバー一覧
          </th>
          <td align="left" valign="middle">
            <% @circle.users.each do |user| %>
              <%= user.display_name %>(<%= user.email %>)
          <% end %>
          </td>

        </tr>
      </table>
    </div>
    <div class="col-6">
      <div id="circle-image">
        <img src='https://mb.api.cloud.nifty.com/2013-09-01/applications/6aJWFXEYlhr6utde/publicFiles/<%= @circle.id %>.jpg' style='width:100%'>
      </div>
      <input type="file" id="file-data"/><input type="button" class="btn btn-primary" value="画像をアップロード" onclick="onFormSend()">
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p><%= link_to 'サークルにメンバーを追加する', new_member_path(@circle), class: "btn btn-info", style: "color:#ffffff" %></p>

      <%= link_to 'Edit', edit_circle_path(@circle) %> |
      <%= link_to 'Back', circles_path %>
    </div>
  </div>
</div>